######################################################################
#   ______    _________________________     ______          ______   #
#  |      \   \                        |   |      \        /      |  #
#  |       \   \    ___________________|   |       \      /       |  #
#  |   |\   \   \   \                      |   |\   \    /   /|   |  #
#  |   | \   \   \   \                     |   | \   \  /   / |   |  #
#  |   |__\   \   \   \     ___________    |   |  \   \/   /  |   |  #
#  |           \   \   \    \          |   |   |   \      /   |   |  #
#  |    ____    \   \   \    \_____    |   |   |    \____/    |   |  #
#  |   |    \    \   \   \         |   |   |   |              |   |  #
#  |   |     \    \   \   \________|   |   |   |              |   |  #
#  |   |      \    \   \               |   |   |              |   |  #
#  |___|       \____\   \______________|   |___|              |___|  #
#                                                                    #
######################################################################
#  AGM Ranks                                                         #
#  Website: https://agmdev.xyz/                                      #
#  Discord: https://agmdev.xyz/discord                               #
#  Wiki: https://github.com/Ashengaurd/AGMEnchants/wiki              #
######################################################################

Prefix: AGMEnchants
Check:
  PluginUpdates: true

  BlacklistedEnchants: []
  BlacklistedRunes: []

Debug:
  Enable: false
  General: true
  Enchants: true
  Runes: true
  Update: true
  GUI: true
  PlaceholderAPI: true

InGameMessages:
  Info: true
  Debug: true
  Warning: true

LoreConfig:
  AboveItemLore: true
  ShowLore: true
  SeparatorLine: '§f------------------------------'
  Compress: false
  CompressLimit: 8

Colors:
  Enchants:
    Normal: '§7'
    Cursed: '§c'
    Treasure: '§b'
  Runes:
    Common: '§7'
    Uncommon: '§a'
    Rare: '§b'
    Epic: '§d'
    Legendary: '§6'

ItemsList:
  SWORDS:
    - NETHERITE_SWORD
    - DIAMOND_SWORD
    - IRON_SWORD
    - GOLD_SWORD
    - STONE_SWORD
    - WOODEN_SWORD
  AXES:
    - NETHERITE_AXE
    - DIAMOND_AXE
    - IRON_AXE
    - GOLD_AXE
    - STONE_AXE
    - WOODEN_AXE
  PICKAXES:
    - NETHERITE_PICKAXE
    - DIAMOND_PICKAXE
    - IRON_PICKAXE
    - GOLD_PICKAXE
    - STONE_PICKAXE
    - WOODEN_PICKAXE
  SHOVELS:
    - NETHERITE_SHOVEL
    - DIAMOND_SHOVEL
    - IRON_SHOVEL
    - GOLD_SHOVEL
    - STONE_SHOVEL
    - WOODEN_SHOVEL
  HOES:
    - NETHERITE_HOE
    - DIAMOND_HOE
    - IRON_HOE
    - GOLD_HOE
    - STONE_HOE
    - WOODEN_HOE
  ARMORS:
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
    - GOLD_HELMET
    - GOLD_CHESTPLATE
    - GOLD_LEGGINGS
    - GOLD_BOOTS
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
  CHESTPLATES:
    - NETHERITE_CHESTPLATE
    - DIAMOND_CHESTPLATE
    - IRON_CHESTPLATE
    - CHAINMAIL_CHESTPLATE
    - GOLD_CHESTPLATE
    - LEATHER_CHESTPLATE
  BOOTS:
    - NETHERITE_BOOTS
    - DIAMOND_BOOTS
    - IRON_BOOTS
    - CHAINMAIL_BOOTS
    - GOLD_BOOTS
    - LEATHER_BOOTS
  LEGGINGS:
    - NETHERITE_LEGGINGS
    - DIAMOND_LEGGINGS
    - IRON_LEGGINGS
    - CHAINMAIL_LEGGINGS
    - GOLD_LEGGINGS
    - LEATHER_LEGGINGS
  HELMET:
    - NETHERITE_HELMET
    - DIAMOND_HELMET
    - IRON_HELMET
    - CHAINMAIL_HELMET
    - GOLD_HELMET
    - LEATHER_HELMET