######################################################################
#   ______    _________________________     ______          ______   #
#  |      \   \                        |   |      \        /      |  #
#  |       \   \    ___________________|   |       \      /       |  #
#  |   |\   \   \   \                      |   |\   \    /   /|   |  #
#  |   | \   \   \   \                     |   | \   \  /   / |   |  #
#  |   |__\   \   \   \     ___________    |   |  \   \/   /  |   |  #
#  |           \   \   \    \          |   |   |   \      /   |   |  #
#  |    ____    \   \   \    \_____    |   |   |    \____/    |   |  #
#  |   |    \    \   \   \         |   |   |   |              |   |  #
#  |   |     \    \   \   \________|   |   |   |              |   |  #
#  |   |      \    \   \               |   |   |              |   |  #
#  |___|       \____\   \______________|   |___|              |___|  #
#                                                                    #
######################################################################
#  AGM Ranks                                                         #
#  Website: https://agmdev.xyz/                                      #
#  Discord: https://agmdev.xyz/discord                               #
#  Wiki: https://github.com/Ashengaurd/AGMEnchants/wiki              #
######################################################################

Prefix: AGMEnchants
Check:
  PluginUpdates: true

  BlacklistedEnchants: []
  BlacklistedRunes: []

Debug:
  Enable: false
  General: true
  Enchants: true
  Runes: true
  Update: true
  GUI: true
  ProtocolLib: true
  PlaceholderAPI: true

InGameMessages:
  Info: true
  Debug: true
  Warning: true