name: AGMEnchants
version: ${project.version}
main: me.ashenguard.agmenchants.AGMEnchants
api-version: 1.13
softdepend: [PlaceholderAPI, Vault]
authors: [Ashenguard]
description: More magics in game
website: https://agmdev.xyz
